# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.IntegerField()),
                ('fullName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('fName', models.CharField(max_length=100)),
                ('mName', models.CharField(max_length=100)),
                ('pNumber', models.CharField(max_length=100)),
                ('pEmail', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
