# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(max_length=100),
        ),
    ]
