# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20181106_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
