# Generated by Django 2.2.7 on 2019-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20181106_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
